export const defaultSettings = {
  EvB: {
    topTextName: 'Excited',
    topTextDescription: 'challenges people to outperform',
    bottomText: 'Bored',
    bottomTextDescription: 'creates disengaged mediocrity',
    color: '#e05345',
    benchmark: 2.5,
    minValue: -50,
    maxValue: 50,
  },
  FvP: {
    topTextName: 'Fulfilled',
    topTextDescription: 'builds ambition and passion',
    bottomText: 'Pointless',
    bottomTextDescription: 'drives carelessness and absenteeism',
    color: '#fd9936',
    benchmark: 17.4,
    minValue: -50,
    maxValue: 50,
  },
  PvE: {
    topTextName: 'Proud',
    topTextDescription: 'drives teamwork and advocacy',
    bottomText: 'Embarrassed',
    bottomTextDescription: 'causes complaints and low morale',
    color: '#ffbf2a',
    benchmark: 20,
    minValue: -50,
    maxValue: 50,
  },
  VvS: {
    topTextName: 'Valuable',
    topTextDescription: 'improves skills, raises confidence',
    bottomText: 'Stuck',
    bottomTextDescription: 'limits initiative and innovation',
    color: '#a4af52',
    benchmark: 13.3,
    minValue: -50,
    maxValue: 50,
  },
  RvD: {
    topTextName: 'Rewarded',
    topTextDescription: 'builds trust and work ethic',
    bottomText: 'Disdained',
    bottomTextDescription: 'fuels bitterness and cynicism',
    color: '#5eafa9',
    benchmark: 14.6,
    minValue: -50,
    maxValue: 50,
  },
  SvT: {
    topTextName: 'Safe',
    topTextDescription: 'promotes focus and collaboration',
    bottomText: 'Threatened',
    bottomTextDescription: 'causes distractions and risk aversion',
    color: '#2a5565',
    benchmark: -19.9,
    minValue: -50,
    maxValue: 50,
  },
  CvD: {
    topTextName: 'Contented',
    topTextDescription: 'builds loyalty and generosity',
    bottomText: 'Despondent',
    bottomTextDescription: 'leads to inertia and increased stress',
    color: '#e799a8',
    benchmark: 12.5,
    minValue: -50,
    maxValue: 50,
  },
};
